templates:
  - name: "diagnosis"
    formats: ["md", "docx"]
    languages: ["fr", "en"]
  - name: "action-plan"
    formats: ["md", "xlsx"]
    languages: ["fr"]
defaults:
  author: "TOGAFrance Contributor"
  date: "auto"
